version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 400
  method-complexity:
    enabled: true
    config:
      threshold: 12
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 30
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 200
  identical-code:
    config:
      threshold: 100
